@baseURL = http://localhost:3333

# @name: List of tasks
GET {{baseURL}}/tasks

###

# @name: Create a task
POST {{baseURL}}/tasks
Content-Type: application/json

{
  "title": "Task 01",
  "description": "Description of task 01"
}